repos:
  - repo: local
    hooks:
      - id: version-bump
        name: Bump Version
        language: system
        entry: python scripts/bump_version.py
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
