repos:
  - repo: local
    hooks:
      - id: version-bump
        name: Bump Version
        entry: python scripts/bump_version.py
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        name: ruff (lint)
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: ruff (format)