repos:
  - repo: local
    hooks:
      - id: version-bump
        name: Bump Version
        entry: python scripts/bump_version.py
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]